package parser

import (
	"testing"

	"github.com/c0m4r/iptables-analyzer/internal/models"
)

const basicRules = `# Generated by iptables-save
*filter
:INPUT DROP [100:5000]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [200:10000]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j DROP
-A INPUT -s 10.0.0.0/8 -p tcp --dport 5432 -j ACCEPT
-A INPUT -j DROP
COMMIT
`

func TestParseBasic(t *testing.T) {
	rs, err := Parse(basicRules, models.IPv4)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(rs.Tables) != 1 {
		t.Fatalf("expected 1 table, got %d", len(rs.Tables))
	}

	filter := rs.Tables["filter"]
	if filter == nil {
		t.Fatal("missing filter table")
	}

	input := filter.Chains["INPUT"]
	if input == nil {
		t.Fatal("missing INPUT chain")
	}

	if input.Policy != "DROP" {
		t.Errorf("expected INPUT policy DROP, got %s", input.Policy)
	}

	if input.Packets != 100 {
		t.Errorf("expected 100 packets, got %d", input.Packets)
	}

	if len(input.Rules) != 6 {
		t.Fatalf("expected 6 INPUT rules, got %d", len(input.Rules))
	}

	// Check rule 1: loopback
	r1 := input.Rules[0]
	if r1.InIface != "lo" || r1.Target != "ACCEPT" {
		t.Errorf("rule 1: expected lo/ACCEPT, got %s/%s", r1.InIface, r1.Target)
	}

	// Check rule 3: SSH
	r3 := input.Rules[2]
	if r3.Protocol != models.ProtoTCP || r3.DstPort != "22" || r3.Target != "ACCEPT" {
		t.Errorf("rule 3: expected tcp/22/ACCEPT, got %s/%s/%s", r3.Protocol, r3.DstPort, r3.Target)
	}

	// Check rule 5: postgres with source
	r5 := input.Rules[4]
	if r5.SrcAddr != "10.0.0.0/8" || r5.DstPort != "5432" {
		t.Errorf("rule 5: expected 10.0.0.0/8:5432, got %s:%s", r5.SrcAddr, r5.DstPort)
	}

	// Check conntrack states
	r2 := input.Rules[1]
	if len(r2.States) != 2 {
		t.Errorf("rule 2: expected 2 states, got %d", len(r2.States))
	}
}

const natRules = `*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.17.0.2:80
COMMIT
`

func TestParseNAT(t *testing.T) {
	rs, err := Parse(natRules, models.IPv4)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	nat := rs.Tables["nat"]
	if nat == nil {
		t.Fatal("missing nat table")
	}

	docker := nat.Chains["DOCKER"]
	if docker == nil {
		t.Fatal("missing DOCKER chain")
	}

	if len(docker.Rules) != 1 {
		t.Fatalf("expected 1 DOCKER rule, got %d", len(docker.Rules))
	}

	rule := docker.Rules[0]
	if rule.Target != "DNAT" {
		t.Errorf("expected DNAT target, got %s", rule.Target)
	}
	if rule.DNATTarget != "172.17.0.2:80" {
		t.Errorf("expected DNAT target 172.17.0.2:80, got %s", rule.DNATTarget)
	}
	if rule.DstPort != "8080" {
		t.Errorf("expected dport 8080, got %s", rule.DstPort)
	}
	if rule.Protocol != models.ProtoTCP {
		t.Errorf("expected tcp protocol, got %s", rule.Protocol)
	}
}

func TestParseComments(t *testing.T) {
	data := `*filter
:INPUT DROP [0:0]
-A INPUT -p tcp --dport 22 -m comment --comment "Allow SSH" -j ACCEPT
COMMIT
`
	rs, err := Parse(data, models.IPv4)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	rule := rs.Tables["filter"].Chains["INPUT"].Rules[0]
	if rule.Comment != "Allow SSH" {
		t.Errorf("expected comment 'Allow SSH', got '%s'", rule.Comment)
	}
}

func TestTokenize(t *testing.T) {
	tests := []struct {
		input    string
		expected int
	}{
		{"-A INPUT -j ACCEPT", 4},
		{`-A INPUT -m comment --comment "hello world" -j DROP`, 8},
		{"-A INPUT ! -p tcp -j DROP", 7},
	}

	for _, tt := range tests {
		tokens := tokenize(tt.input)
		if len(tokens) != tt.expected {
			t.Errorf("tokenize(%q): expected %d tokens, got %d: %v", tt.input, tt.expected, len(tokens), tokens)
		}
	}
}
